apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web.name" . }}
    helm.sh/chart: {{ include "web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ toYaml .Values.nginx.config | indent 2 }}
