apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webservice.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "webservice.name" . }}
    helm.sh/chart: {{ include "webservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ toYaml .Values.app.envVars | indent 2 }}